In [24]:
import numpy as np 
import pandas as pd

In [25]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder

In [26]:
df=pd.read_csv('/Users/siddharthkushwaha/Desktop/ML/day-28-coloumn-trans/covid_toy.csv')

In [27]:
df.head()

   age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [28]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [29]:

from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df.drop(columns=['has_covid']),df['has_covid'],
                                                test_size=0.2)

In [30]:
X_train

    age  gender  fever   cough       city
55   81  Female  101.0    Mild     Mumbai
38   49  Female  101.0    Mild      Delhi
94   79    Male    NaN  Strong    Kolkata
79   48  Female  103.0    Mild    Kolkata
63   10    Male  100.0    Mild  Bangalore
..  ...     ...    ...     ...        ...
26   19  Female  100.0    Mild    Kolkata
43   22  Female   99.0    Mild  Bangalore
64   42    Male  104.0    Mild     Mumbai
49   44    Male  104.0    Mild     Mumbai
25   23    Male    NaN    Mild     Mumbai

[80 rows x 5 columns]

### 1. Aam Zindagi

In [31]:
# adding simple imputer to fever col
si = SimpleImputer()
X_train_fever = si.fit_transform(X_train[['fever']])

# also the test data
X_test_fever = si.fit_transform(X_test[['fever']])
                                 
X_train_fever.shape

(80, 1)

In [33]:
from sklearn.preprocessing import OneHotEncoder

ohe = OneHotEncoder(drop='first', sparse_output=False)

# Train data
X_train_gender_city = ohe.fit_transform(X_train[['gender', 'city']])

# Test data
X_test_gender_city = ohe.transform(X_test[['gender', 'city']])

print(X_train_gender_city.shape)
print(X_test_gender_city.shape)

(80, 4)
(20, 4)

In [34]:

# Extracting Age
X_train_age = X_train.drop(columns=['gender','fever','cough','city']).values

# also the test data
X_test_age = X_test.drop(columns=['gender','fever','cough','city']).values

X_train_age.shape

(80, 1)

In [36]:
X_train_transformed = np.concatenate(
    (X_train_age,
     X_train_fever,
     X_train_gender_city,
     X_train_cough),
    axis=1
)

X_test_transformed = np.concatenate(
    (X_test_age,
     X_test_fever,
     X_test_gender_city,
     X_test_cough),
    axis=1
)

X_train_transformed.shape

NameError: name 'X_train_cough' is not defined

### Mentos Zindagi

In [38]:
transformer = ColumnTransformer(transformers=[
    ('tnf1',SimpleImputer(),['fever']),
    ('tnf2',OrdinalEncoder(categories=[['Mild','Strong']]),['cough']),
    ('tnf3',OneHotEncoder(sparse=False,drop='first'),['gender','city'])
],remainder='passthrough')

NameError: name 'ColumnTransformer' is not defined